// <auto-generated />
using System;
using DataNex.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataNex.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240128121501_AddedCustomer")]
    partial class AddedCustomer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataNex.Model.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BPhone1")
                        .HasColumnType("int");

                    b.Property<int?>("BPhone2")
                        .HasColumnType("int");

                    b.Property<string>("BPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SPhone1")
                        .HasColumnType("int");

                    b.Property<int?>("SPhone2")
                        .HasColumnType("int");

                    b.Property<string>("SPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SRegion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("datanex_customers");
                });

            modelBuilder.Entity("DataNex.Model.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("datanex_users");
                });
#pragma warning restore 612, 618
        }
    }
}
